name: lamino
channels:
  - conda-forge
  - https://software.repos.intel.com/python/conda
  - ccpi

dependencies:
  - python=3.12
  - ccpi::cil=24.3.0
  - numpy=1.26
  - astra-toolbox=2.1=cuda*
  - ccpi::tigre=2.6
  - ccpi::ccpi-regulariser=24.0.1
  - ipykernel 
  - ipywidgets 
  - scikit-image
  - scikit-learn
  - matplotlib-base >=3.3.0
  - pip
  - pip:
    - gvxr>=2.0.10